version: "3.8"

services:
  mail-forwarder:
    image: zixia/simple-mail-forwarder
    container_name: mail-forwarder
    restart: always
    ports:
      - "25:25"                         # проброс SMTP-порта
    environment:
      SMF_CONFIG: "@recipely.ru:your@gmail.com"
